name: release

on:
  workflow_dispatch:
    inputs:
      comment:
        description: comment  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
